"""
metadata_importer.py

Imports forensic metadata generated by
Member 5.

Supports:
- JSON
- XML (Future)
- CSV (Future)

Creates a Metadata object without
reading the original file.
"""

import json
from pathlib import Path
from datetime import datetime

from ..models.metadata import Metadata


class MetadataImporter:
    """
    Imports forensic metadata.
    """

    @staticmethod
    def import_json(json_file: str) -> Metadata:

        path = Path(json_file)

        if not path.exists():
            raise FileNotFoundError(
                f"Metadata file not found: {json_file}"
            )

        with open(path, "r", encoding="utf-8") as file:
            data = json.load(file)

        return Metadata(

            # Basic Information

            file_name=data["file_name"],
            extension=data["extension"],
            mime_type=data["mime_type"],
            size=data["size"],

            # Location

            absolute_path=data["absolute_path"],
            parent_directory=data["parent_directory"],

            # Time Information

            created_time=datetime.fromisoformat(
                data["created_time"]
            ),

            modified_time=datetime.fromisoformat(
                data["modified_time"]
            ),

            accessed_time=datetime.fromisoformat(
                data["accessed_time"]
            ),

            # Owner

            owner=data["owner"],

            # Investigation

            evidence_type=data.get(
                "evidence_type",
                "UNKNOWN"
            ),

            evidence_id=data["evidence_id"],

            hash_algorithm=data.get(
                "hash_algorithm",
                "SHA-256"
            ),

            hash_value=data.get(
                "hash_value"
            ),

            case_id=data.get(
                "case_id"
            )
        )