class EPRAEngine:
    """
    Calculates the final EPRA score
    using the Adaptive Decision Matrix weights.
    """

    def calculate_score(self, factor_values: dict, weights: dict) -> float:
        """
        Returns the final EPRA score.

        Parameters
        ----------
        factor_values : dict
            {
                "semantic": 0.90,
                "authenticity": 0.80,
                "context": 0.60,
                "investigation": 0.70,
                "behaviour": 0.30
            }

        weights : dict
            Generated by WeightGenerator.
        """

        score = 0.0

        for factor, weight in weights.items():
            value = factor_values.get(factor, 0.0)
            score += value * weight

        return round(score, 4)