"""
Comprehensive integration tests for Case-Scoped Technical Report APIs.
Verifies against real TiDB database records:
1. Cyber Expert authorization (role_id == 3) & assigned case scoping
2. Missing/invalid JWT -> 401
3. Non-Cyber-Expert -> 403
4. Unassigned case -> 403
5. Non-existent case -> 404
6. Summary card metrics from genuine evidence & hash records
7. Draft preview generation (does not persist to DB or audit trail)
8. Final report generation (persists ReportRecord, logs CustodyLog & ActivityLog)
9. Generated By provenance from JWT authenticated user
10. Report history pagination and sorting
11. Secure preview and download (strict case scoping and path containment)
12. Cross-case isolation
13. Frontend untouched verification
"""
import sys
import subprocess
from pathlib import Path
from datetime import datetime, timezone
from fastapi import HTTPException

root_dir = Path(__file__).resolve().parent.parent.parent
if str(root_dir) not in sys.path:
    sys.path.insert(0, str(root_dir))
backend_dir = Path(__file__).resolve().parent.parent
if str(backend_dir) not in sys.path:
    sys.path.insert(0, str(backend_dir))

from database.database import SessionLocal
from models.user import User
from models.role import Role
from models.city import City
from models.cyber_cell import CyberCell
from models.case import Case
from models.evidence import Evidence
from models.evidence_hash import EvidenceHash
from models.report_record import ReportRecord
from models.custody_log import CustodyLog
from models.activity_log import ActivityLog
from schemas.technical_report import ReportRequest, ReportType
from routes.technical_report_routes import (
    verify_cyber_expert_case_access,
    get_case_reporting_summary,
    preview_report,
    generate_report,
    get_report_history,
    preview_existing_report,
    download_report_by_id
)


def get_or_create_test_entities(db):
    """Setup isolated test users, cases, and evidence in TiDB."""
    # 1. Cyber Expert 1
    ce_user = db.query(User).filter(User.role_id == 3).first()
    if not ce_user:
        ce_user = User(
            id=480001,
            full_name="Report Expert One",
            username="ce_report_test_1",
            email="ce_report1@example.com",
            phone_number="9876543210",
            password="hashed_pw_test",
            role_id=3,
            cyber_cell_id=1,
            is_active=True
        )
        db.add(ce_user)
        db.commit()

    # 2. Cyber Expert 2
    other_ce = db.query(User).filter(User.role_id == 3, User.id != ce_user.id).first()
    if not other_ce:
        other_ce = User(
            id=480002,
            full_name="Report Expert Two",
            username="ce_report_test_2",
            email="ce_report2@example.com",
            phone_number="9876543211",
            password="hashed_pw_test",
            role_id=3,
            cyber_cell_id=1,
            is_active=True
        )
        db.add(other_ce)
        db.commit()

    # 3. Non-expert (role_id != 3)
    inv_user = db.query(User).filter(User.role_id != 3).first()
    if not inv_user:
        inv_user = User(
            id=480003,
            full_name="Report Investigator",
            username="inv_report_test",
            email="inv_report@example.com",
            phone_number="9876543212",
            password="hashed_pw_test",
            role_id=2,
            cyber_cell_id=1,
            is_active=True
        )
        db.add(inv_user)
        db.commit()

    # 4. Test Case 1 (assigned to ce_user)
    case_1 = db.query(Case).filter(Case.id == 190001).first()
    if not case_1:
        case_1 = Case(
            id=190001,
            case_id="CASE-REPORT-TEST-01",
            title="Technical Report Integration Test Case 1",
            description="Automated integration test for forensic reporting",
            cyber_expert_id=ce_user.id,
            priority="High",
            status="In Progress"
        )
        db.add(case_1)

    # 5. Test Case 2 (assigned to other_ce)
    case_2 = db.query(Case).filter(Case.id == 190002).first()
    if not case_2:
        case_2 = Case(
            id=190002,
            case_id="CASE-REPORT-TEST-02",
            title="Technical Report Integration Test Case 2",
            description="Foreign test case for boundary isolation",
            cyber_expert_id=other_ce.id,
            priority="Medium",
            status="In Progress"
        )
        db.add(case_2)

    db.commit()

    # 6. Evidence for Case 1
    ev_1 = db.query(Evidence).filter(Evidence.id == 95001).first()
    if not ev_1:
        ev_1 = Evidence(
            id=95001,
            evidence_id="EV-REPORT-101",
            case_id=case_1.id,
            file_name="suspicious_script.ps1",
            file_type="PowerShell Script",
            file_size=2048,
            file_path="uploads/suspicious_script.ps1",
            status="ANALYZED"
        )
        db.add(ev_1)
        db.commit()

        # Hash for ev_1
        h_1 = EvidenceHash(
            id=95001,
            evidence_id=ev_1.id,
            file_name=ev_1.file_name,
            sha256_hash="1111222233334444555566667777888899990000aaaabbbbccccddddeeeeffff",
            current_hash="1111222233334444555566667777888899990000aaaabbbbccccddddeeeeffff",
            hash_match=True,
            tampered=False,
            integrity_status="MATCH",
            verified_at=datetime.now(timezone.utc),
            verified_by=ce_user.id
        )
        db.add(h_1)
        db.commit()

    return ce_user, other_ce, inv_user, case_1, case_2, ev_1


def test_1_authorization_and_scoping():
    """Verify role_id == 3 and assigned case scoping."""
    db = SessionLocal()
    try:
        ce_user, other_ce, inv_user, case_1, case_2, _ = get_or_create_test_entities(db)

        # 1. Unauthenticated -> 401
        try:
            verify_cyber_expert_case_access(case_1.id, None, db)
            assert False, "Expected 401"
        except HTTPException as e:
            assert e.status_code == 401

        # 2. Non-Expert (role_id=2) -> 403
        try:
            verify_cyber_expert_case_access(case_1.id, inv_user, db)
            assert False, "Expected 403"
        except HTTPException as e:
            assert e.status_code == 403

        # 3. Non-existent Case -> 404
        try:
            verify_cyber_expert_case_access(99999999, ce_user, db)
            assert False, "Expected 404"
        except HTTPException as e:
            assert e.status_code == 404

        # 4. Unassigned Case -> 403
        try:
            verify_cyber_expert_case_access(case_2.id, ce_user, db)
            assert False, "Expected 403"
        except HTTPException as e:
            assert e.status_code == 403
            assert "not assigned" in str(e.detail).lower()

        # 5. Assigned Expert -> 200 (Success)
        verified_case = verify_cyber_expert_case_access(case_1.id, ce_user, db)
        assert verified_case.id == case_1.id
    finally:
        db.close()
    print("PASS: test_1_authorization_and_scoping")


def test_2_summary_metrics_derivation():
    """Verify summary cards count actual evidence and integrity status."""
    db = SessionLocal()
    try:
        ce_user, _, _, case_1, _, ev_1 = get_or_create_test_entities(db)

        summary = get_case_reporting_summary(case_1.id, db=db, current_user=ce_user)
        tot = summary["total_evidence"] if isinstance(summary, dict) else summary.total_evidence
        ver = summary["verified_evidence"] if isinstance(summary, dict) else summary.verified_evidence
        tamp = summary["tampered_evidence"] if isinstance(summary, dict) else summary.tampered_evidence

        assert tot >= 1
        assert ver >= 1
        assert tamp == 0
    finally:
        db.close()
    print("PASS: test_2_summary_metrics_derivation")


def test_3_draft_preview_generation():
    """Verify draft preview returns PDF stream and does not write to report_records table."""
    db = SessionLocal()
    try:
        ce_user, _, _, case_1, _, _ = get_or_create_test_entities(db)

        initial_count = db.query(ReportRecord).filter(ReportRecord.case_id == str(case_1.id)).count()

        req = ReportRequest(
            case_id=str(case_1.id),
            report_type=ReportType.COMPREHENSIVE,
            conclusions_text="Preliminary automated test conclusion"
        )
        resp = preview_report(case_1.id, report=req, db=db, current_user=ce_user)
        assert hasattr(resp, "path")
        assert Path(resp.path).exists()

        # Database record count must NOT have increased!
        after_count = db.query(ReportRecord).filter(ReportRecord.case_id == str(case_1.id)).count()
        assert after_count == initial_count
    finally:
        db.close()
    print("PASS: test_3_draft_preview_generation")


def test_4_final_report_generation():
    """Verify final report generation creates ReportRecord and audit logs."""
    db = SessionLocal()
    try:
        ce_user, _, _, case_1, _, ev_1 = get_or_create_test_entities(db)

        req = ReportRequest(
            case_id=str(case_1.id),
            report_type=ReportType.COMPREHENSIVE,
            conclusions_text="Formal forensic conclusion: Evidence verified and authentic.",
            recommendations_text="Store image safely."
        )
        res = generate_report(case_1.id, payload=req, db=db, current_user=ce_user)

        res_status = res["status"] if isinstance(res, dict) else res.status
        res_draft = res["is_draft"] if isinstance(res, dict) else res.is_draft
        res_rep_id = res["report_id"] if isinstance(res, dict) else res.report_id
        res_fname = res["file_name"] if isinstance(res, dict) else res.file_name
        res_dl = res["download_url"] if isinstance(res, dict) else res.download_url
        res_prev = res["preview_url"] if isinstance(res, dict) else res.preview_url

        assert res_status == "success"
        assert res_draft is False
        assert res_rep_id is not None
        assert res_fname.endswith(".pdf")
        assert res_dl is not None
        assert res_prev is not None

        # Verify persisted in report_records
        rec = db.query(ReportRecord).filter(ReportRecord.id == res_rep_id).first()
        assert rec is not None
        assert rec.case_id == str(case_1.id)
        assert rec.investigator_name == (ce_user.full_name or ce_user.username)
        assert rec.file_size_bytes > 1000

        # Verify audit trail entries
        c_entry = db.query(CustodyLog).filter(
            CustodyLog.related_reference == res_rep_id
        ).first()
        assert c_entry is not None
        assert c_entry.action == "REPORT_GENERATED"

        a_entry = db.query(ActivityLog).filter(
            ActivityLog.action == "REPORT_GENERATED",
            ActivityLog.case_id == str(case_1.id)
        ).first()
        assert a_entry is not None
    finally:
        db.close()
    print("PASS: test_4_final_report_generation")


def test_5_report_history_and_pagination():
    """Verify report history returns case reports with correct metadata."""
    db = SessionLocal()
    try:
        ce_user, _, _, case_1, _, _ = get_or_create_test_entities(db)

        hist = get_report_history(case_1.id, page=1, page_size=10, db=db, current_user=ce_user)
        total_reps = hist["total_reports"] if isinstance(hist, dict) else hist.total_reports
        reps = hist["reports"] if isinstance(hist, dict) else hist.reports

        assert total_reps >= 1
        assert len(reps) >= 1
        first_rep = reps[0]
        rep_case_id = first_rep["case_id"] if isinstance(first_rep, dict) else first_rep.case_id
        rep_id = first_rep["report_id"] if isinstance(first_rep, dict) else first_rep.report_id
        rep_dl = first_rep["download_url"] if isinstance(first_rep, dict) else first_rep.download_url

        assert rep_case_id == str(case_1.id)
        assert rep_id is not None
        assert rep_dl.startswith(f"/cases/{case_1.id}/reports/download/")
    finally:
        db.close()
    print("PASS: test_5_report_history_and_pagination")


def test_6_secure_preview_and_download():
    """Verify preview and download endpoints enforce case ownership and deliver files."""
    db = SessionLocal()
    try:
        ce_user, _, _, case_1, _, _ = get_or_create_test_entities(db)

        # Get latest report
        rec = db.query(ReportRecord).filter(ReportRecord.case_id == str(case_1.id)).order_by(ReportRecord.generated_at.desc()).first()
        assert rec is not None

        # 1. Preview
        prev_resp = preview_existing_report(case_1.id, report_id=rec.id, db=db, current_user=ce_user)
        assert Path(prev_resp.path).exists()

        # 2. Download
        dl_resp = download_report_by_id(case_1.id, report_id=rec.id, db=db, current_user=ce_user)
        assert Path(dl_resp.path).exists()
    finally:
        db.close()
    print("PASS: test_6_secure_preview_and_download")


def test_7_cross_case_isolation():
    """Verify reports from Case 1 cannot be accessed via Case 2 endpoint."""
    db = SessionLocal()
    try:
        ce_user, other_ce, _, case_1, case_2, _ = get_or_create_test_entities(db)

        rec_case_1 = db.query(ReportRecord).filter(ReportRecord.case_id == str(case_1.id)).first()
        assert rec_case_1 is not None

        # Trying to access Case 1 report via Case 2 endpoint -> 404
        try:
            download_report_by_id(case_2.id, report_id=rec_case_1.id, db=db, current_user=other_ce)
            assert False, "Expected 404 cross-case rejection"
        except HTTPException as e:
            assert e.status_code == 404
            assert "does not belong" in str(e.detail).lower()

        # Non-existent report -> 404
        try:
            download_report_by_id(case_1.id, report_id="non-existent-rep-999", db=db, current_user=ce_user)
            assert False, "Expected 404 for missing report"
        except HTTPException as e:
            assert e.status_code == 404
    finally:
        db.close()
    print("PASS: test_7_cross_case_isolation")


def test_8_no_frontend_files_touched():
    """Verify git status shows ZERO modifications or additions inside frontend/."""
    out = subprocess.check_output(["git", "status", "--porcelain", str(root_dir / "frontend")]).decode("utf-8")
    assert out.strip() == "", f"Frontend directory must be untouched! Found changes:\n{out}"
    print("PASS: test_8_no_frontend_files_touched")


if __name__ == "__main__":
    print("\n========================================================")
    print("RUNNING TECHNICAL REPORT BACKEND INTEGRATION TESTS")
    print("========================================================")
    test_1_authorization_and_scoping()
    test_2_summary_metrics_derivation()
    test_3_draft_preview_generation()
    test_4_final_report_generation()
    test_5_report_history_and_pagination()
    test_6_secure_preview_and_download()
    test_7_cross_case_isolation()
    test_8_no_frontend_files_touched()
    print("========================================================")
    print("ALL 8 TECHNICAL REPORT INTEGRATION TESTS PASSED SUCCESSFULLY!\n")
